/*===========================================================================
     _____        _____        _____        _____
 ___|    _|__  __|_    |__  __|__   |__  __| __  |__  ______
|    \  /  | ||    \      ||     |     ||  |/ /     ||___   |
|     \/   | ||     \     ||     \     ||     \     ||___   |
|__/\__/|__|_||__|\__\  __||__|\__\  __||__|\__\  __||______|
    |_____|      |_____|      |_____|      |_____|

--[Mark3 Realtime Platform]--------------------------------------------------

Copyright (c) 2012-2015 Funkenstein Software Consulting, all rights reserved.
See license.txt for more information
===========================================================================*/
/*!

    \file   message.cpp    

    \brief  Inter-thread communications via message passing

*/

#include "kerneltypes.h"
#include "mark3cfg.h"

#include "message.h"
#include "threadport.h"

#define _CAN_HAS_DEBUG
//--[Autogenerated - Do Not Modify]------------------------------------------
#include "dbg_file_list.h"
#include "buffalogger.h"
#if defined(DBG_FILE)
# error "Debug logging file token already defined!  Bailing."
#else
# define DBG_FILE _DBG___KERNEL_MESSAGE_CPP
#endif
//--[End Autogenerated content]----------------------------------------------
#include "kerneldebug.h"

#if KERNEL_USE_MESSAGE

#if KERNEL_USE_TIMEOUTS
	#include "timerlist.h"
#endif

Message GlobalMessagePool::m_aclMessagePool[GLOBAL_MESSAGE_POOL_SIZE];
DoubleLinkList GlobalMessagePool::m_clList;

//---------------------------------------------------------------------------
void GlobalMessagePool::Init()
{
	uint8_t i;
    GlobalMessagePool::m_clList.Init();
    for (i = 0; i < GLOBAL_MESSAGE_POOL_SIZE; i++)
	{
		GlobalMessagePool::m_aclMessagePool[i].Init();
		GlobalMessagePool::m_clList.Add(&(GlobalMessagePool::m_aclMessagePool[i]));
	}
}

//---------------------------------------------------------------------------
void GlobalMessagePool::Push( Message *pclMessage_ )
{
	KERNEL_ASSERT( pclMessage_ );
	
	CS_ENTER();
		
	GlobalMessagePool::m_clList.Add(pclMessage_);
	
	CS_EXIT();
}
	
//---------------------------------------------------------------------------
Message *GlobalMessagePool::Pop()
{
	Message *pclRet;
	CS_ENTER();
	
	pclRet = static_cast<Message*>( GlobalMessagePool::m_clList.GetHead() );
    if (0 != pclRet)
    {
        GlobalMessagePool::m_clList.Remove( static_cast<LinkListNode*>( pclRet ) );
    }
	
	CS_EXIT();
	return pclRet;
}

//---------------------------------------------------------------------------
void MessageQueue::Init() 
{ 
    m_clSemaphore.Init(0, GLOBAL_MESSAGE_POOL_SIZE);
}

//---------------------------------------------------------------------------
Message *MessageQueue::Receive()
{
#if KERNEL_USE_TIMEOUTS
    return Receive_i(0);
#else
    return Receive_i();
#endif
}

//---------------------------------------------------------------------------
#if KERNEL_USE_TIMEOUTS
Message *MessageQueue::Receive( uint32_t u32TimeWaitMS_)
{
    return Receive_i( u32TimeWaitMS_ );
}
#endif

//---------------------------------------------------------------------------
#if KERNEL_USE_TIMEOUTS
Message *MessageQueue::Receive_i( uint32_t u32TimeWaitMS_ )
#else
Message *MessageQueue::Receive_i( void )
#endif
{
	Message *pclRet;
	
	// Block the current thread on the counting semaphore
#if KERNEL_USE_TIMEOUTS
    if (!m_clSemaphore.Pend(u32TimeWaitMS_))
    {
        return NULL;
    }
#else
    m_clSemaphore.Pend();
#endif
	
	CS_ENTER();
	
	// Pop the head of the message queue and return it
	pclRet = static_cast<Message*>( m_clLinkList.GetHead() );
	m_clLinkList.Remove(static_cast<Message*>(pclRet));
	
	CS_EXIT();
	
	return pclRet;	
}

//---------------------------------------------------------------------------
void MessageQueue::Send( Message *pclSrc_ )
{
	KERNEL_ASSERT( pclSrc_ );
	
	CS_ENTER();
	
	// Add the message to the head of the linked list
	m_clLinkList.Add( pclSrc_ );
		
	// Post the semaphore, waking the blocking thread for the queue.
	m_clSemaphore.Post();
	
	CS_EXIT();
}

//---------------------------------------------------------------------------
uint16_t MessageQueue::GetCount()
{
	return m_clSemaphore.GetCount();
}
#endif //KERNEL_USE_MESSAGE
