/*===========================================================================
     _____        _____        _____        _____
 ___|    _|__  __|_    |__  __|__   |__  __| __  |__  ______
|    \  /  | ||    \      ||     |     ||  |/ /     ||___   |
|     \/   | ||     \     ||     \     ||     \     ||___   |
|__/\__/|__|_||__|\__\  __||__|\__\  __||__|\__\  __||______|
    |_____|      |_____|      |_____|      |_____|

--[Mark3 Realtime Platform]--------------------------------------------------

Copyright (c) 2012-2015 Funkenstein Software Consulting, all rights reserved.
See license.txt for more information
===========================================================================*/
/*!

    \file   blocking.cpp

    \brief  Implementation of base class for blocking objects
*/

#include "kerneltypes.h"
#include "mark3cfg.h"

#include "blocking.h"
#include "thread.h"

#define _CAN_HAS_DEBUG
//--[Autogenerated - Do Not Modify]------------------------------------------
#include "dbg_file_list.h"
#include "buffalogger.h"
#if defined(DBG_FILE)
# error "Debug logging file token already defined!  Bailing."
#else
# define DBG_FILE _DBG___KERNEL_BLOCKING_CPP
#endif
//--[End Autogenerated content]----------------------------------------------
#include "kerneldebug.h"

#if KERNEL_USE_SEMAPHORE || KERNEL_USE_MUTEX
//---------------------------------------------------------------------------
void BlockingObject::Block(Thread *pclThread_)
{
	KERNEL_ASSERT( pclThread_ );
    KERNEL_TRACE_1( "Blocking Thread %d", (uint16_t)pclThread_->GetID() );
	
    // Remove the thread from its current thread list (the "owner" list)
    // ... And add the thread to this object's block list
    Scheduler::Remove(pclThread_);
    m_clBlockList.Add(pclThread_);
    
    // Set the "current" list location to the blocklist for this thread
    pclThread_->SetCurrent(&m_clBlockList);
    pclThread_->SetState(THREAD_STATE_BLOCKED);
}

//---------------------------------------------------------------------------
void BlockingObject::BlockPriority(Thread *pclThread_)
{
    KERNEL_ASSERT( pclThread_ );
    KERNEL_TRACE_1( "Blocking Thread %d", (uint16_t)pclThread_->GetID() );

    // Remove the thread from its current thread list (the "owner" list)
    // ... And add the thread to this object's block list
    Scheduler::Remove(pclThread_);
    m_clBlockList.AddPriority(pclThread_);

    // Set the "current" list location to the blocklist for this thread
    pclThread_->SetCurrent(&m_clBlockList);
    pclThread_->SetState(THREAD_STATE_BLOCKED);
}

//---------------------------------------------------------------------------
void BlockingObject::UnBlock(Thread *pclThread_)
{
	KERNEL_ASSERT( pclThread_ );
    KERNEL_TRACE_1( "Unblocking Thread %d", (uint16_t)pclThread_->GetID() );
    
	// Remove the thread from its current thread list (the "owner" list)
    pclThread_->GetCurrent()->Remove(pclThread_);
    
    // Put the thread back in its active owner's list.  This is usually
    // the ready-queue at the thread's original priority.    
    Scheduler::Add(pclThread_);
    
    // Tag the thread's current list location to its owner
    pclThread_->SetCurrent(pclThread_->GetOwner());
    pclThread_->SetState(THREAD_STATE_READY);
}

#endif
